#!/usr/bin/env python3
"""Regenerate po/clipman.pot from the files listed in po/POTFILES.in.

Extraction uses pygettext, which ships with CPython, so translators and
CI need no extra system package. The header is rewritten afterwards so
the template is byte-identical on every run for unchanged sources.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POTFILES = ROOT / "po" / "POTFILES.in"
POT = ROOT / "po" / "clipman.pot"

# Fixed so the template does not change on its own each January. Bump it
# together with the notice in LICENSE and NOTICE.
COPYRIGHT_YEAR = "2026"

HEADER = """\
# Clipman translation template.
# Copyright (C) {COPYRIGHT_YEAR} Clipman Contributors
# This file is distributed under the Apache-2.0 license.
#
# Generated by scripts/gen-pot.py — do not edit by hand.
#
msgid ""
msgstr ""
"Project-Id-Version: Clipman {version}\\n"
"Report-Msgid-Bugs-To: https://github.com/MohammedEl-sayedAhmed/clipman/issues\\n"
"POT-Creation-Date: \\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"
"Language-Team: LANGUAGE <LL@li.org>\\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"""


def source_files():
    files = []
    for line in POTFILES.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            files.append(line)
    if not files:
        sys.exit("po/POTFILES.in lists no source files")
    missing = [f for f in files if not (ROOT / f).is_file()]
    if missing:
        sys.exit(f"po/POTFILES.in lists missing files: {', '.join(missing)}")
    return files


def extract(files, out_path):
    for tool in ("pygettext3", "pygettext"):
        try:
            subprocess.run(
                [tool, "-d", "clipman", "-o", str(out_path), *files],
                cwd=ROOT, check=True, capture_output=True, text=True,
            )
            return
        except FileNotFoundError:
            continue
        except subprocess.CalledProcessError as exc:
            sys.exit(f"{tool} failed:\n{exc.stderr}")
    sys.exit("pygettext3 not found; it ships with python3 — install python3-dev "
             "or run: python3 -m pip install python-gettext")


def version():
    text = (ROOT / "clipman" / "_version.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__ = "([^"]+)"', text, re.M)
    return match.group(1) if match else "0.0.0"


def main():
    files = source_files()
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "clipman.pot"
        extract(files, raw)
        body = raw.read_text(encoding="utf-8")

    # Drop pygettext's own header: everything up to the blank line that
    # follows the empty msgid block.
    marker = '"Generated-By: pygettext'
    index = body.find(marker)
    if index != -1:
        index = body.find("\n", index)
        body = body[index + 1:]
    body = body.lstrip("\n")

    POT.write_text(
        HEADER.format(version=version(), COPYRIGHT_YEAR=COPYRIGHT_YEAR) + "\n" + body,
        encoding="utf-8",
    )
    count = sum(1 for line in body.splitlines() if line.startswith("msgid "))
    print(f"po/clipman.pot: {count} strings from {len(files)} files")


if __name__ == "__main__":
    main()
